### ISSUE TITLE
rust.rs:762:69

### ISSUE THREAD

**Issue by ghost** [forensicxlab/VISION-ProcMon#3]
My System:
Win-11
npm-9.6.2
-----
C:\Users\x\Downloads\VISION-ProcMon>npm run tauri build

> vision-procmon@1.0.0 tauri
> tauri build

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', src\interface\rust.rs:762:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by forensicxlab** [comment]
Hello J2033, 
Please make sure you followed the tauri prerequisites before building the project : https://tauri.app/v1/guides/getting-started/prerequisites.

I do not own WIN11, but I will make sure to test the project build on a VM and get back to you.

Best regards.

**Comment by forensicxlab** [comment]
Project build worked on WIN11. 
Closing the issue.
